# Copyright 2018-2022 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

api = "0.7"

[buildpack]
  description = "A Cloud Native Buildpack that contributes the AppInternals Agent and configures it to connect to the service"
  homepage = "https://github.com/paketo-buildpacks/aternity"
  id = "paketo-buildpacks/aternity"
  keywords = ["riverbed", "aternity", "agent", "apm", "java"]
  name = "Paketo Buildpack for Aternity"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/aternity/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "bin/build", "bin/detect", "bin/helper", "bin/main", "buildpack.toml"]
  pre-package = "scripts/build.sh"

  [[metadata.dependencies]]
    cpes = ["cpe:2.3:a:aternity:steelcentral_appinternals:11.8.5:*:*:*:*:*:*:*"]
    id = "appinternals-java"
    name = "Aternity AppInternals Java Agent"
    purl = "pkg:generic/aternity-appinternals-java-agent@11.8.5?arch=amd64"
    sha256 = "8242054c1828196a5605ac8225f2fdf3a947931c3e4db6e2e4b26df70bbaffe0"
    stacks = ["io.buildpacks.stacks.bionic", "io.paketo.stacks.tiny", "*"]
    uri = "https://pcf-instrumentation-download.steelcentral.net/riverbed-appinternals-agent-11.8.5_BL527.zip"
    version = "11.8.5"

    [[metadata.dependencies.licenses]]
      uri = "https://www.riverbed.com/document/legal/riverbed-end-user-license-agreement.pdf"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"

[[stacks]]
  id = "io.paketo.stacks.tiny"

[[stacks]]
  id = "*"
